### ISSUE TITLE
-

### ISSUE THREAD

**Issue by bigbug-gg** [Fluox-Etine/EvoAdmin#1]
没有效果，就不知道到底要不要安装，希望补上截图。

**Comment by Fluox-Etine** [comment]
哥哥安装文档补上了，都是常规文档，示例demo也上了

**Comment by bigbug-gg** [comment]
Nice! 好的，本来是通过github看到本项目，后来在 webman 的社区看到了此项目的帖子，在该论坛上有示例和效果截图，
就把这个 issues 关闭了, 没想到你还补全了，👍
